# Basic config File
wdir: "working directory"
sdir: "reads input dir"
rdir: "output dir"

tmp: "tmp"
sample_file_read: "sample information file"

tax_db: "database to search against e.g. gtdb"

###############################################################################
#
# Common config values
#
###############################################################################
#Add binary paths
seqkit_bin: "seqkit"
mmseqs_bin: "/vol/cloud/louis/apps/MMseqs2/build/bin/mmseqs"
penguin_bin: "/vol/cloud/louis/apps/plass/build/bin/plass"
carpedeam2_bin: "/vol/cloud/louis/apps/CarpeDeam7/build/bin/plass"
megahit_bin: "/vol/cloud/louis/apps/MEGAHIT-1.2.9-Linux-x86_64-static/bin/megahit"
spades_bin: "/vol/cloud/louis/apps/SPAdes-3.15.5-Linux/bin/metaspades.py"
minimap2_bin: /vol/cloud/louis/apps/minimap2-2.26_x64-linux/minimap2
quast_bin: "metaquast.py"
prodigal_bin: "prodigal"
bowtie2_bin: "bowtie2"
bowtie2_build_bin: "bowtie2-build"
samtools_bin: "/vol/cloud/louis/apps/samtools-1.19/bin/samtools"


# Program parameters
# Threads
seqkit_threads: 16
extract_threads: 8
threads_16: 16
threads_4: 4
threads_8: 8
threads_32: 32
norm_threads: 32
read_rename_threads: 16
assm_input_threads: 16
quast_threads: 16
# Rename reads
rename_reads: True
read_minlen: 30
rename_parms: "addunderscore=f overwrite=t"

# PENGUIN
penguin_threads: 32
penguin_config:
  config0: '--remove-tmp-files 1 --split-memory-limit 200G --max-seq-len 10000000 --min-contig-len 500 -e 0.01'


# CARPEDEAM
carpedeam2_threads: 32
carpedeam2_config:
  config0: '--remove-tmp-files 1 --max-seq-len 100000000 --min-contig-len 500 -e 0.001 --min-length 10 --alph-size nucl:4,aa:13 --split-memory-limit 200G --num-iterations nucl:9,aa:1 -k nucl:20,aa:11 --clust-min-seq-id 0.97 --clust-min-cov 0.97 --min-seq-id nucl:0.9,aa:0.95 --kmer-per-seq-scale 0.3 --include-only-extendable 0 --ignore-multi-kmer 1 --min-ryseq-id 0.99 --min-merge-seq-id 0.985 --correction-min-ry-seqid 0.999 --ry-size-matcher 22 --clust-min-ry-seq-id 0.99 --correction-min-seqid 0.9 --ext-random-align 0.85 --likelihood-ratio-threshold 0.95 --num-iter-reads-only 3'

assm_input_1: ["raw"]
assm_input_2: ["raw"]

# SPADES: assembly
spades_min_contig_length: 500
spades_threads: 32
spades_config: 
  config0: "--only-assembler"

# MEGAHIT: assembly
megahit_min_contig_length: 500
megahit_threads: 32
megahit_config: 
  config0: ""

# MAPPING READS TO CONTIGS
bowtie2_threads: 16
bowtie2_map_mode: "--very-sensitive-local --threads 32"

# MAPPING CONTIGS TO REFERENCE
minimap_threads: 16

# MMSEQS taxonomy
mmseqs_tax_threads: 32

# QUAST validation
ref_folder: ""

# PRODIGAL: gene prediction
prodigal_threads: 1

